services:
  pgadmin:
    image: docker.io/dpage/pgadmin4:latest
    ports:
      - '8088:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=dbuser@example.com
      - PGADMIN_DEFAULT_PASSWORD=change_me
    depends_on:
      db:
        condition: service_healthy

  db:
    image: docker.io/library/postgres:latest
    container_name: pg-for-keycloak
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=change_me
      - POSTGRES_DB=keycloak
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data:Z

  kc:
    build: kc
    container_name: kc-1
    depends_on:
      db:
        condition: service_healthy
    environment:
      - KC_HTTP_ENABLED=true
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=change_me
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://pg-for-keycloak:5432/keycloak
      - KC_DB_USERNAME=dbuser
      - KC_DB_PASSWORD=change_me
      - KC_HOSTNAME=pg-for-keycloak
    command: 'start --optimized --hostname=http://localhost:8080'
  second-kc:
    image: localhost/keycloak-with-podman_kc:latest
    container_name: kc-2
    depends_on:
      kc:
        condition: service_healthy
    environment:
      - KC_HTTP_ENABLED=true
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=change_me
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak-with-podman_db_1:5432/keycloak
      - KC_DB_USERNAME=dbuser
      - KC_DB_PASSWORD=change_me
      - KC_HOSTNAME=keycloak-with-podman_db_1
    command: 'start --optimized --hostname=http://localhost:8080'

  lb:
    image: nginx:latest
    volumes:
      - type: bind
        source: ./lb/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
    ports:
      - 8080:80
    depends_on:
      - second-kc

volumes:
  pgdata:
    driver: local